version: "2"

linters:
  default: none
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - misspell
    - bodyclose
    - lll

  settings:
    lll:
      line-length: 120

formatters:
  enable:
    - gofmt
